MODELS: ["XGBClassifier"]
TRAIN_DATA_PATH: "dataset/Predictive modeling - football-match-probability-prediction/train.csv"
ENCODE_OUTPUT: True
OVERSAMPLE: True
# VAL_RATIO: 0.2
# SEED: 42

# If don't have give any column to transfer please do not provide columntransformer
PARAM_GRID: {
}

GRID_SEARCH_CV_CONFIG: {
  "scoring": "accuracy",
  "cv": 5,
  "return_train_score": True,
  "refit": True
}
